### ISSUE TITLE
Step docstring conflicts with implementation

### ISSUE THREAD

**Issue by thomasjpfan** [neptune-ml/steppy#115]
In the `Step` docstring, it states that `force_fitting` is False by default. The implementation has `force_fitting=True` as the default.

**Comment by kamil-kaczmarek** [comment]
@thomasjpfan thanks. Let me correct docstring. `force_fitting=True` is better default behavior, because it will do training by default, unless you explicitly say not to do it.

**Comment by kamil-kaczmarek** [comment]
Hey @thomasjpfan, I corrected the docstring. Will make new release together with some code changes.
