### ISSUE TITLE
cache outputs in memory

### ISSUE THREAD

**Issue by taraspiotr** [neptune-ml/steppy#46]
It would be great to have a possibility to cache steps outputs in memory.
Right now caching outputs by dumping them onto a hard disk and then loading them back can take longer than simply running the same step all over again.

Implementation:
* each step should have flag, if User wants to cache outputs in memory,
    * if yes, output from transformer should be cached i.e. `my_step.cache_output_in_mem = data`

**Comment by kamil-kaczmarek** [comment]
implemented in #103
