### ISSUE TITLE
Concat features 

### ISSUE THREAD

**Issue by tankz0r** [neptune-ml/steppy#71]
How is it possible to do the following Step in new version(use of ```pandas_concat_inputs```)?:
```gaf_step = Step(name='GroupbyAggregationsFeatures',
                                    transformer=GroupbyAggregationsFeatures(AGGREGATION_RECIPIES),
                                    input_steps=[df_step],
                                    input_data=['input'],
                                    adapter=Adapter({
                                        'X': ([('input', 'X'),
                                               (df_step.name, 'X')],
                                              pandas_concat_inputs)
                                    }),
                                    cache_dirpath=config.env.cache_dirpath)

**Comment by kamil-kaczmarek** [comment]
@grzes314 can you provide quick answer to @tankz0r question? :) Thx

**Comment by tankz0r** [comment]
You need to update your docstrings, because there is old syntax: 
```  step_3 = Step(name='step_3',
                                   input_steps=[step_1, step_2],
                                   input_data=['input_2'],
                                   adapter = {'X':([('step_1','X_transformed'),
                                                    ('step_2','X_transformed'),
                                                    ('step_2','categorical_features'),
                                                    ('input_2','auxilary_features'),
                                                   ], hstack_inputs)
                                              'y':(['input_1', 'y'])
                                             }
and also the same is used in steppy-examples https://github.com/minerva-ml/steppy-examples/blob/master/tutorials/simple_step_example.ipynb

**Comment by tankz0r** [comment]
I understood how it should be. This way right? 
```gather_stepgather_  = Step(
    name='gather_step',
    transformer=make_transformer(lambda lst: {'X': pandas_concat_inputs(lst)}),
    input_steps=[df_step],
    input_data=['input'],
    adapter=Adapter({
        'lst': [E('input', 'X'), E(df_step.name, 'X')]
    }),
    cache_dirpath=config.env.cache_dirpath
)

**Comment by tankz0r** [comment]
Well in the way I mentioned earlier it works, however, I need to create one additional Step. Is it possible somehow to do in one line like it was previously? 
```                                    adapter=Adapter({
                                        'X': ([('input', 'X'),
                                               (df_step.name, 'X')],
                                              pandas_concat_inputs)
                                    }),

**Comment by kamil-kaczmarek** [comment]
Hi @tankz0r, you are right that the syntax from here https://github.com/minerva-ml/steppy-examples/blob/master/tutorials/simple_step_example.ipynb is outdated. By Friday we will have new version of code `steppy-0.1.2` and docstrings changed accordingly.

New way of adapting inputs is preferred. This is because you do not leak any processing outside `step.transformer` which happened in case of passing function like `hstack_inputs` to arrange inputs in some way.

You can still use it in old way by directly taking the `steps` code from our [open-solution-avito-demand-prediction](https://github.com/minerva-ml/open-solution-avito-demand-prediction/tree/0ac2e875aa6a2ad7afff8e794bf4f3109c0db9bf/steps). This link points you to the particular commit.

Best,
Kamil

**Comment by tankz0r** [comment]
Is it any difference between results of these two code samples(because I get the same answer in both)? What is the purpose to use Adapter in this case? 
![selection_099](https://user-images.githubusercontent.com/13698885/41164655-5fe2ebce-6b44-11e8-8e95-0053c144fbe0.png)

**Comment by kamil-kaczmarek** [comment]
Hi @tankz0r, in this can there is no difference. By default Step take 'X', so adapting inputs is identity here: `X -> X`
Adapter is not obligatory attribute of the `Step` class.

**Comment by kamil-kaczmarek** [comment]
seems like answer is satisfactory. Closing this :+1:
