### ISSUE TITLE
How to evaluate each step only once? 

### ISSUE THREAD

**Issue by tankz0r** [neptune-ml/steppy#72]
I have the following structure of my steps. The problem is that many steps are called more than once and it makes the process of training very slow. Is it possible somehow to simplify it? 
more precisely, how to optimize this part? I would like to compute ```input_missing``` just once
![selection_105](https://user-images.githubusercontent.com/13698885/41346881-a309e248-6f10-11e8-9702-9db7fdbaee34.png)

**Comment by kamil-kaczmarek** [comment]
Hi @tankz0r,
Set `Step.cache_output=True`, so after `fit_transform()` or `transform()` steppy will cache outputs and just load them in consecutive calls to this step.

Let me know, if it worked for you :)

**Comment by kamil-kaczmarek** [comment]
BTW @tankz0r, what features you need, besides these already available?

**Comment by tankz0r** [comment]
you mean for ```Steppy```?

**Comment by kamil-kaczmarek** [comment]
Hi @tankz0r, Documentation: https://steppy.readthedocs.io/en/latest/ Mind that it is still under construction, and we are improving it weekly :)

`steppy-toolkit` is complementary to the steppy. Our goal is to create very high quality implementations (with docs of course) of mostly `Transformers` that are ready to use in your steppy-based pipeline. For example you just do:
```
from toolkit.pytorch_recipes.models import MultiOutputUnet

my_step = Step(name='U-Net_segmentation',
               transformer=MultiOutputUnet(**parameters),
               input_steps=[preprocessing],
               persist_output=True)

```
and parametrize it in a way you want. All `Tranformers` will have the same Interface. The overall goal is to make sort of _data scientist inventory_ of ready-to-use pieces of pipelines :)
