### ISSUE TITLE
Do we really need a transformer to be cached to perform transform()?

### ISSUE THREAD

**Issue by apyskir** [neptune-ml/steppy#73]
Now the situation is as follows:
if I want to run Step.transform(data) the transformer of this step needs to be cached in an experiment directory.
I don't think it is necessary if the transformer is not fittable, like in postprocessing or preprocessing steps.
I would suggest, that if a transformer has non-trivial `fit()` method, it should be cached to perform `transform()`, otherwise it doesn't need to be cached, because in the cached file there is actually no data.
Now, when I have pipeline:
preprocessing step -> neural network step -> postprocessing step
I need to perform postprocessing on all my training data (to create all necessary transformers), which is redundant and often time consuming, OR I can manually create trivial transformer file. I think it should be simplified.

**Comment by kamil-kaczmarek** [comment]
implemented in #103. There is flag `is_fittable` 
thanks @apyskir !
