### ISSUE TITLE
difficult debugging

### ISSUE THREAD

**Issue by taraspiotr** [neptune-ml/steppy#84]
It is really hard to debug when an error is raised inside a `Step` instance, it would be great if steppy returned a stack trace with at least a name of a step inside which the error had been raised.

**Comment by kamil-kaczmarek** [comment]
Hi @taraspiotr,

In the 0.1.8 version, we have implemented this. So from now on, error in the transformer (fit_transform or transform) will result in error log that start with step name and transformer name.
