### ISSUE TITLE
Let's pass `experiment_directory` only once per pipeline

### ISSUE THREAD

**Issue by apyskir** [neptune-ml/steppy#85]
Now one have to pass `experiment_directory` parameter to every step in a pipeline. It is quite inconvenient. I propose to prepare a mechanism, in which a step is passing its `experiment_directory` to its input steps. This way one will need to define `experiment_directory` once per pipeline - in the last step of the pipeline.

**Comment by kamil-kaczmarek** [comment]
@apyskir @stared, 
We implemented this in version 0.1.8 -> ability to set parameter to all upstream steps relative to the current step. For example:
```
new_path = {'experiment_directory': '/YOUR/PATH/GOES/HERE'}
Step.set_parameters_upstream(new_path)
# voila :)
# all steps upstream to the current step (including current) have parameter `experiment_directory` set to `/YOUR/PATH/GOES/HERE`.
```

Best,
Kamil
