### ISSUE TITLE
Difference between cache and persist

### ISSUE THREAD

**Issue by tankz0r** [neptune-ml/steppy#88]
I do not really get the difference between these two things. 
Both of them cache the result of execution in the disc. 
![selection_114](https://user-images.githubusercontent.com/13698885/42699197-b4adbd1a-86c8-11e8-8668-8ede9b046b89.png)
Is it a good idea to add cache_output to all the Steps to avoid any executions twice? 
In some of your examples, you use both cache and persist at the same time, I think it is a good idea to use one of it... 
![selection_115](https://user-images.githubusercontent.com/13698885/42699415-5e4d3df0-86c9-11e8-9f00-b56515a8d520.png)

**Comment by kamil-kaczmarek** [comment]
seems like question is covered. Closing this :)
