### ISSUE TITLE
logger's path and filename

### ISSUE THREAD

**Issue by fengyonglv** [neptune-ml/steppy#90]
I want to know ,how to define output logger's path and logger's filename.
Thanks

**Comment by jakubczakon** [comment]
Hi there @fengyonglv sorry for late reply.
As of now we do not have this option and the logger is defined in steppy.utils statically.

We should get it sorted some time soon but for now feel free to submit a PR with that functionality.

**Comment by fengyonglv** [comment]
Thanks your reply.
I look forward to add this option in the future.
