### ISSUE TITLE
Does stepper have a CONTRIBUTING?

### ISSUE THREAD

**Issue by bcottman** [neptune-ml/steppy#93]

**Comment by bcottman** [comment]
Well I know there is a CONTRIBUTING invitation. but..... what I think is a good example, look at   https://pandas.pydata.org/pandas-docs/stable/contributing.html 

if so desired I can produce the a version

**Comment by jakubczakon** [comment]
That would be amazing @bcottman . Thank you very much!

**Comment by kamil-kaczmarek** [comment]
Hi @bcottman 

It is very desired! You can make use of https://github.com/neptune-ml/steppy-examples if you wish.

On our side we are going to improve/refresh documentation, so definitely that will be valuable contribution.

Let us know if you need some support in this matter.

Thank you!
Kamil

**Comment by bcottman** [comment]
starting work on this today..

Regards Bruce

**Comment by kamil-kaczmarek** [comment]
Hi @bcottman,

First of all, that you for this initiative! This is so much needed and appreciated.

If I understand you correctly you will contribute `sphinx_rtd_theme` documentation to the steppy, right?
If so, I also encourage you to just initialize docs in steppy-toolkit -> then I will contribute some docs (contents) there.

Best,
Kamil Kaczmarek

**Comment by bcottman** [comment]
i will try and create and test step-toolkit/docs today. i will use sphinx_rtd_theme. I am using .ipynb instead of .rtf. 

very much later.. with  prob 0.03%...  will probably create bash macros and maybe get ambitious and turn them into sphinx extensions. but... i get way ahead of myself

**Comment by bcottman** [comment]
have finished rough draft of CONTRIB and FAQ. i use .ipynb instead of .rst and thus broke the build environment. will try ad fix today.

**Comment by bcottman** [comment]
0.01 pushed

**Comment by bcottman** [comment]
Maybe one of you would like to talk about Steppy I don’t feel qualified to do do. Also anyone that is  a Kaggler who uses cloud services should switch to Neptune, imho.

You might also talk about Neptune in comparison to tensorboard,torchvision,etc

Regards bruce

Begin forwarded message:

> From: Rich Bowen <rbowen@apache.org>
> Date: September 11, 2018 at 10:05:52 AM EST
> To: apachecon-discuss@apache.org
> Subject: Speakers needed for Apache DC Roadshow
> Reply-To: apachecon-discuss@apache.org, rbowen@apache.org
> 
> We need your help to make the Apache Washington DC Roadshow on Dec 4th a success.
> 
> What do we need most? Speakers!
> 
> We're bringing a unique DC flavor to this event by mixing Open Source Software with talks about Apache projects as well as OSS CyberSecurity, OSS in Government and and OSS Career advice.
> 
> Please take a look at: http://www.apachecon.com/usroadshow18/
> 
> (Note: You are receiving this message because you are subscribed to one or more mailing lists at The Apache Software Foundation.)
> 
> Rich, for the ApacheCon Planners
> 
> -- 
> rbowen@apache.org
> http://apachecon.com
> @ApacheCon
> 
> ---------------------------------------------------------------------
> To unsubscribe e-mail: dev-unsubscribe@spark.apache.org
>

**Comment by bcottman** [comment]
Now this will be a big event. Let me if someone can give a talk. You might consider leading with Neptune with Steppy being the opensource arm. Could be the next sparc!


P.s. giving a talk is worth 10 Kaggle events.
Regards Bruce 


Begin forwarded message:

> From: O'Reilly Media <reply@oreilly.com>
> Date: September 12, 2018 at 7:05:29 PM EST
> To: dr.bruce.cottman@gmail.com
> Subject: Want to speak at the AI Conference in 2019?
> Reply-To: reply@oreilly.com
> 
> 
> 
> Learning Platform • Conferences • Ideas
>  
> April 15–18
> New York, NY	
> “A rare opportunity to meet some of most brilliant minds in AI.”
> —S. Kayyali, AI Engineer
> Hi Bruce,
> Every year, the AI community gathers at the AI Conference New York to discover the latest developments new use cases and best practices in AI and to share rock-solid technical skills and inspiration. It's happening in 2019 April 15–18.
> This is a rare opportunity to get a true cross-pollination of ideas—and to share the stage with some of the most interesting and innovative minds in AI. Previous speakers have included Michael Jordan, Peter Norvig, Kai-Fu Lee, Meredith Whittaker, Matt Wood, Amy Unruh, Lili Cheng, and Andrew Ng.
> If you've got a great idea, a compelling case study, a teardown of a successful AI project (or dissection of a failure), or deep technical expertise to share, this is a great opportunity to make your mark.
> The deadline to submit a proposal to speak is October 16.
> We're looking forward to hearing your best ideas,
> Apply to speak
> Ben Lorica, Naveen Rao, and Roger Chen
> Program Chairs
> P.S. If you have a colleague you think has a lot to share in the area of applied AI, forward this email to them as a nudge of encouragement.
> Presented by
> 	
> Thank you to our sponsors
> Contributing Sponsor
> 
> For exhibition and sponsorship opportunities, email aisponsorships@oreilly.com
>  	 	 	 
> This message was sent to dr.bruce.cottman@gmail.com. You are receiving this because you're a customer of O'Reilly Media, or you've signed up to receive email from us. We hope you found this message to be useful. However, if you'd rather not receive future emails of this type from O'Reilly, please manage your preferences or unsubscribe here.
> Please read our Privacy Policy.
> O'Reilly Media, Inc. 1005 Gravenstein Highway North, Sebastopol, CA 95472 (707) 827-7000

**Comment by kamil-kaczmarek** [comment]
Hey @bcottman, thanks for providing us with these great opportunities.

Regarding the _Apache DC Roadshow_ -> we do not know this conference, so - at least at this point - we cannot commit to it.
Regarding _AI Conference New York_ -> as of now, I think that steppy will not fit in the format of this big, corporate-oriented event. We are bringing value to the hands-on data scientists, while the audience of the AI-NY is different.

For further ideas like this (conferences) I would prefer to talk privately via e-mail :smiley:

Best,
Kamil A. Kaczmarek

**Comment by bcottman** [comment]
Kamil,
Ok. But I do not seem to have your e-mail. I suppose I could find it but I usually follow protocol of the person sending me the email. 

Hint: full starter doc for Steppy and Steppy-toolkit now for merge. Iike code I can see several areas that need re-write. In future, all my code will include unit and docstring.

- bruce
